include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    no_default_cases: false
    use_named_constants: false
    avoid_positional_boolean_parameters: false
    comment_references: false
    require_trailing_commas: false
    depend_on_referenced_packages: false

    unawaited_futures: false
    use_build_context_synchronously: false
    use_setters_to_change_properties: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    overridden_fields: true
    parameter_assignments: true
    avoid_dynamic_calls: false

analyzer:
  language:
    strict-raw-types: false

  errors:
    todo: false
    fixme: false

  exclude:
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "bin/cache/**"
