include: package:lints/recommended.yaml

# info(true/false): it lines blue to warn
  
linter:
  rules:
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_const: false
    prefer_single_quotes: true
    constant_identifier_names: false
    prefer_final_fields: true
    library_private_types_in_public_api: true
    annotate_overrides: false
    prefer_interpolation_to_compose_strings: false
    prefer_collection_literals: false
    prefer_conditional_assignment: false
    prefer_function_declarations_over_variables: false
    no_leading_underscores_for_local_identifiers: false
    prefer_if_null_operators: true
    prefer_equal_for_default_values: false
    overridden_fields: false
    unnecessary_string_interpolations: true
    avoid_single_cascade_in_expression_statements: false
    avoid_renaming_method_parameters: false
    avoid_returning_null_for_void: false
    avoid_function_literals_in_foreach_calls: false
    always_use_package_imports: true
    camel_case_extensions: true
    depend_on_referenced_packages: false
    prefer_typing_uninitialized_variables: false
    void_checks: false
    prefer_is_empty: false
    curly_braces_in_flow_structures: false


    # prefer_const_constructors_in_immutable: false
    # avoid_unnecessary_containers: false
    # always_declare_return_types: false
    # cancel_subscriptions: false
    # close_sinks: false
    # comment_references: false
    # one_member_abstracts: false
    # only_throw_errors: false
    # package_api_docs: false
    # prefer_final_in_for_each: false
    # avoid_print: false
    # avoid_web_libraries_in_flutter: false
    # no_logic_in_create_state: false
    # prefer_const_declarations: false
    # prefer_const_literals_to_create_immutables: false
    # sort_child_properties_last: false
    # use_build_context_synchronously: false
    # use_full_hex_values_for_flutter_colors: false

# error: it lines red and will not let you compile anymore
# warning: lines yellow 
analyzer:
  errors:
    todo: false 
    fixme: false 
    prefer_iterable_wheretype: false
    prefer_for_elements_to_map_fromiterable: false

