include: package:lints/recommended.yaml

# warnings(true/false): it lines blue to warn

  
linter:
  rules:
    # always_use_package_imports: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutable: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true

    always_declare_return_types: false
    cancel_subscriptions: false
    close_sinks: false
    comment_references: false
    one_member_abstracts: false
    only_throw_errors: false
    package_api_docs: false
    prefer_final_in_for_each: false
    avoid_print: false
    avoid_web_libraries_in_flutter: false
    no_logic_in_create_state: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    sort_child_properties_last: false
    use_build_context_synchronously: false
    use_full_hex_values_for_flutter_colors: false

# error: it lines red and will not let you compile anymore
# warning: lines yellow 
# analyzer:
#   errors:
#     todo: false 


