include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    no_default_cases: false
    use_named_constants: false
    avoid_positional_boolean_parameters: false
    comment_references: false

    invalid_assignment: true
    omit_local_variable_types: true
    prefer_final_locals: true
    avoid_final_parameters: true
    type_annotate_public_apis: true
    always_declare_return_types: true
    prefer_asserts_with_message: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    unnecessary_const: true
    constant_identifier_names: true
    sort_child_properties_last: true
    sort_constructors_first: true
    prefer_constructors_over_static_methods: true
    sort_unnamed_constructors_first: true
    use_decorated_box: true
    sized_box_shrink_expand: true
    use_colored_box: true
    prefer_if_elements_to_conditional_expressions: true
    avoid_print: true
    prefer_is_empty: true
    unnecessary_raw_strings: true
    one_member_abstracts: true
    use_string_buffers: true
    unnecessary_parenthesis: true
    unnecessary_null_checks: true
    unnecessary_await_in_return: true
    prefer_final_in_for_each: true
    void_checks: true
    avoid_returning_null_for_void: true
    avoid_function_literals_in_foreach_calls: true
    avoid_unnecessary_containers: true
    noop_primitive_operations: true
    missing_whitespace_between_adjacent_strings: true

    avoid_dynamic_calls: false
    require_trailing_commas: false
    cascade_invocations: false
    unnecessary_lambdas: false
    unawaited_futures: false
    use_build_context_synchronously: false
    prefer_int_literals: false
    avoid_redundant_argument_values: false
    cast_nullable_to_non_nullable: false
    only_throw_errors: false
    overridden_fields: false
    no_leading_underscores_for_local_identifiers: false
    avoid_renaming_method_parameters: false
    parameter_assignments: false
    depend_on_referenced_packages: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    prefer_typing_uninitialized_variables: false
    join_return_with_assignment: false
    use_if_null_to_convert_nulls_to_bools: false
    avoid_field_initializers_in_const_classes: false
    prefer_function_declarations_over_variables: false
    no_logic_in_create_state: false
    avoid_escaping_inner_quotes: false
    use_setters_to_change_properties: false
    avoid_single_cascade_in_expression_statements: false
    avoid_void_async: false
    prefer_conditional_assignment: false
    prefer_null_aware_method_calls: false

analyzer:

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: false

  errors:
    invalid_assignment: true
    argument_type_not_assignable: true
    return_of_invalid_type: true
    map_key_type_not_assignable: true
    non_bool_operand: true
    return_of_invalid_type_from_closure: true
    list_element_type_not_assignable: true
    non_bool_negation_expression: true
    non_bool_condition: true
    prefer_iterable_wheretype: true
    prefer_for_elements_to_map_fromiterable: true
    # todo and fixme
    todo: false
    fixme: false

  exclude:
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "bin/cache/**"
    - assets/translations