name: encointer

sdkPath: ".flutter"

packages:
  - "*"
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  format:
    exec: flutter format . --line-length 120
    description: "Format all Dart code"

  format-check:
    exec: flutter format . --line-length 120 --set-exit-if-changed
    description: "Check format all Dart code"

  analyze:
    exec: flutter analyze
    description: "Analyze all Dart code"

  analyze-check:
    exec: flutter analyze --fatal-warnings
    description: "Analyze all Dart code and exit if there are any fatal warnings"

  clean:
    exec: flutter clean
    description: "Clean pub dependencies"

  pub-get:
    exec: flutter pub get
    description: "Get pub dependencies"

  unit-test:
    exec: flutter test
    description: "Run unit tests (all packages)"

  doctor:
    exec: flutter doctor
    description: "Run Flutter doctor"

  generate-build-runner:
    run: melos exec --depends-on="build_runner"  flutter pub run build_runner build --delete-conflicting-outputs
    description: "Generate code with build_runner"

  yarn-build:
    run: melos exec --dir-exists="lib/js_service_encointer" "cd lib/js_service_encointer/ && yarn install && yarn run build"
    description: "Install yarn dependencies and build"

  # Unit test Encointer Wallet with tag
  unit-test-encointer-exclude-node-e2e:
    run: melos exec --scope="encointer_wallet" -- flutter test --exclude-tags encointer-node-e2e
    description: "Run unit tests excluding the `encointer-node-e2e` tag"

  unit-test-encointer-node-e2e:
    run: melos exec --scope="encointer_wallet" -- flutter test --tags encointer-node-e2e
    description: "Run unit tests with the `encointer-node-e2e` tag"

  unit-test-packages:
    run: melos exec --ignore="encointer_wallet" -- flutter test
    description: "Run unit tests with the `encointer-node-e2e` tag"  

  # Run Encointer Wallet
  run-android:
    run: melos exec --scope="encointer_wallet" -- flutter run --flavor dev
    description: "Run encointer_wallet on an Android platform"

  run-ios:
    run: melos exec --scope="encointer_wallet" -- flutter run
    description: "Run encointer_wallet on an iOS platform"

  # Build apk and appbundle Encointer Wallet
  build-apk:
    run: melos exec --scope="encointer_wallet" -- flutter build apk --flavor fdroid
    description: "Build an APK file"

  build-appbundle:
    run: melos exec --scope="encointer_wallet" -- flutter build appbundle
    description: "Build an appbundle file"

  # Integration test Encointer Wallet
  integration-app-test-android:
    run: melos exec --scope="encointer_wallet" -- flutter drive --target=test_driver/app.dart --flavor dev
    description: "Run integration tests for the `app.dart` file on Android"

  integration-app-test-ios:
    run: melos exec --scope="encointer_wallet" -- flutter drive --target=test_driver/app.dart
    description: "Run integration tests for the `app.dart` file on iOS"

  integration-real-app-test-android:
    run: melos exec --scope="encointer_wallet"-- flutter drive --target=test_driver/real_app.dart --flavor dev
    description: "Run integration tests for the `real_app.dart`` file on Android"

  integration-real-app-test-ios:
    run: melos exec --scope="encointer_wallet" -- flutter drive --target=test_driver/real_app.dart
    description: "Run integration tests for the `real_app.dart`` file on IOS"

  integration-scan-test-android:
    run: melos exec --scope="encointer_wallet" -- flutter drive --target=test_driver/scan_page.dart --flavor dev
    description: "Run integration test for QR scan on Android"

  integration-scan-test-ios:
    run: melos exec --scope="encointer_wallet" -- flutter drive --target=test_driver/scan_page.dart
    description: "Run integration test for QR scan on iOS"
