include: package:lints/recommended.yaml

linter:
  rules:
    # Generated files don't satisfy this.
    avoid_renaming_method_parameters: false
    no_leading_underscores_for_local_identifiers: false
    type_literal_in_constant_pattern: false
    unintended_html_in_doc_comment: false