name: ew_primitives
description: Primitives for Encointer
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  ew_keyring: 0.1.0
  ew_polkadart: 0.1.0
  ew_substrate_fixed: 0.1.0

dev_dependencies:
  test: ^1.24.9
  very_good_analysis: ^10.0.0
