name: ew_primitives
description: Primitives for Encointer
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ew_keyring:
    path: ../ew_keyring
  ew_polkadart:
    path: ../ew_polkadart
  ew_substrate_fixed:
    path: ../ew_substrate_fixed

dev_dependencies:
  test: ^1.24.9
  very_good_analysis: ^5.1.0
