name: ew_primitives
description: Primitives for Encointer
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ew_keyring:
    path: ../ew_keyring
  ew_polkadart:
    path: ../ew_polkadart
  ew_substrate_fixed:
    path: ../ew_substrate_fixed

dev_dependencies:
  test: ^1.24.9
  very_good_analysis: ^5.1.0

# We have to use dependency overrides as the polkadart_cli in our fork uses
# the published package as dependency. We can remove them when we use the
# published package.
dependency_overrides:
  polkadart_scale_codec:
    #    path: ../../../polkadart/packages/polkadart_scale_codec
    git:
      url: https://github.com/encointer/polkadart
      ref: main
      path: packages/polkadart_scale_codec
  polkadart_keyring:
    #    path: ../../../polkadart/packages/polkadart_keyring
    git:
      url: https://github.com/encointer/polkadart
      ref: main
      path: packages/polkadart_keyring
