include: package:very_good_analysis/analysis_options.4.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    directives_ordering: false
