name: ew_models
description: Encointer Models Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: 1.22.0
  very_good_analysis: ^3.1.0
