name: ew_models
description: Encointer Models Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.1
  test: 1.24.3
  very_good_analysis: ^5.1.0
