arb-dir: lib/l10n/arb
output-dir: lib/l10n/gen
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: .untranslated-messages.txt
synthetic-package: false
