import 'dart:convert';

import 'package:encointer_wallet/store/encointer/types/communities.dart';
import 'package:encointer_wallet/utils/enum.dart';

class CommunityReputation {
  CommunityReputation(this.communityIdentifier, this.reputation);

  CommunityIdentifier communityIdentifier;
  Reputation reputation;

  @override
  String toString() {
    return jsonEncode(this);
  }

  // enum does not work with the autogenerated methods.
  factory CommunityReputation.fromJson(Map<String, dynamic> json) {
    return CommunityReputation(
      CommunityIdentifier.fromJson(json['communityIdentifier'] as Map<String, dynamic>),
      reputationFromString(json['reputation'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{'communityIdentifier': communityIdentifier, 'reputation': reputation.toValue()};
  }
}

enum CeremonyPhase { Registering, Assigning, Attesting }

CeremonyPhase ceremonyPhaseFromString(String value) {
  return getEnumFromString(CeremonyPhase.values, value);
}

enum Reputation { Unverified, UnverifiedReputable, VerifiedUnlinked, VerifiedLinked }

Reputation reputationFromString(String value) {
  return getEnumFromString(Reputation.values, value);
}

extension reputationExtension on Reputation {
  String toValue() {
    return toEnumValue(this);
  }
}

extension ceremonyPhaseExtension on CeremonyPhase {
  String toValue() {
    return toEnumValue(this);
  }
}
