import 'package:encointer_wallet/utils/enum.dart';

class CommunityReputation {
  CommunityReputation(this.communityIdentifier, this.reputation);

  int communityIdentifier;
  Reputation reputation;

  // enum does not work with the autogenerated methods.
  factory CommunityReputation.fromJson(Map<String, dynamic> json) =>
      CommunityReputation(json['communityIdentifier'] as int, reputationFromString(json['reputation'] as String));

  Map<String, dynamic> toJson() =>
      <String, dynamic>{'communityIdentifier': communityIdentifier, 'reputation': reputation.toValue()};
}

enum CeremonyPhase { Registering, Assigning, Attesting }

CeremonyPhase ceremonyPhaseFromString(String value) {
  return getEnumFromString(CeremonyPhase.values, value);
}

enum Reputation { Unverified, UnverifiedReputable, VerifiedUnlinked, VerifiedLinked }

Reputation reputationFromString(String value) {
  return getEnumFromString(Reputation.values, value);
}

extension reputationExtension on Reputation {
  String toValue() {
    return toEnumValue(this);
  }
}

extension ceremonyPhaseExtension on CeremonyPhase {
  String toValue() {
    return toEnumValue(this);
  }
}
