name: ew_substrate_fixed
description: Implements fixed point handling in dart
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  test: ^1.24.9
  very_good_analysis: ^9.0.0
