name: ew_format
description: Encointer Fromat Package
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
