arb-dir: lib/src/arb
output-dir: lib/src/gen
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: .untranslated-messages.txt
