name: App Integration Test (iPhone)

on:
  push:
    branches: [ master, gihtub-action-integration-tests ]
  pull_request:
    branches: [ master ]

env:
  flutter_version: '2.0.1'

jobs:
  ios_device_test:
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "iPhone 11 Pro Max"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: marceloprado/has-changed-path@v1
          id: js-changed
          with:
            paths: ./lib/js_service_encointer
      - name: "Cache JS"
        id: cache-js
        uses: actions/cache@v2
        with:
          path: ./lib/js_service_encointer/dist/main.js
          key: ${{ runner.os }}-main.js
      - name: "Build JS if needed"
        if: steps.js-changed.outputs.changed == 'true' && steps.cache-js.outputs.cache-hit != 'true'
        run: source ./init_env.sh && ./build_js.sh
#      - name: "Build JS"
#        working-directory: ./scripts
#        run: source ./init_env.sh && ./build_js.sh
      - run: flutter pub get
      - name: "Start Simulator"
        working-directory: ./scripts
        env:
          DEVICE_ID: ${{ matrix.device }}
        run: source ./ios.sh
      - name: "Flutter driver test and record video"
        working-directory: ./scripts
        run: source ./init_env.sh && ./ios_integration_test.sh
        env:
          TEMP_DIR: /tmp/encointer-wallet/
      - name: "Upload Recording"
        uses: actions/upload-artifact@v2
        with:
          name: recording
          path: /tmp/encointer-wallet/


