# File is copy-pasted and adapted from Integritee worker:
# https://github.com/integritee-network/worker/blob/1a58d6a625fa76935902f16c798efa453bcef9a4/.github/workflows/label-checker.yml

name: Check labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, ready_for_review]

jobs:
    check_for_matching_labels:
      runs-on: ubuntu-latest
      if: github.base_ref == 'master' && github.event.pull_request.draft == false
      strategy:
        fail-fast: false
        matrix:
          include:
            - test: A-change-type
              enforced_labels: "A0-UX,A1-BugFix,A2-Technical"
            - test: B-urgency
              enforced_labels: "B0-Low,B1-Medium,B2-Critical"
            - test: C-breaking-changes
              enforced_labels: "C0-BreaksNothing,C1-BreaksApi"
      steps:
        - name: Label check
          run: |
            MATCH=$(jq -cn '${{ toJSON(github.event.pull_request.labels.*.name) }} as $USER_LABELS |
            ${{ toJSON(matrix.enforced_labels)  }} | split(",") as $LABELS |
            $USER_LABELS - ($USER_LABELS - $LABELS)')
            if [[  "$MATCH" == '[]' ]]; then
                exit 1
            fi
