name: IOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  ios_device_test:
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - device: "iPhone 11 Pro Max"
            record_video: true
          - device: "iPhone 8 Plus"
            record_video: false
          - device: "iPad Pro (12.9-inch) (3rd generation)"
            record_video: false
          - device: "iPad Pro (12.9-inch) (2nd generation)"
            record_video: false
      fail-fast: false
    steps:
        # Setup Environment
      - uses: actions/checkout@v2
        with:
          # 2 to compare the last two revisions to check if JS changed
          fetch-depth: 2

      - uses: monorepo-actions/config-for-actions@main
        id: config
        with:
          config_files: ./.github/action-config.json

      - name: "Prepare environment for ios"
        working-directory: ./scripts
        run: ./ios_init_env.sh

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.config.outputs.java-version }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.config.outputs.flutter-version }}

      - name: "Create Simulator if iPad Pro 2nd gen"
        if: ${{ matrix.device == 'iPad Pro (12.9-inch) (2nd generation)' }}
        run: xcrun simctl create "iPad Pro (12.9-inch) (2nd generation)" "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-" "com.apple.CoreSimulator.SimRuntime.iOS-15-2"

      - name: "Create Simulator if iPad Pro 3rd gen"
        if: ${{ matrix.device == 'iPad Pro (12.9-inch) (3rd generation)' }}
        run: xcrun simctl create "iPad Pro (12.9-inch) (3rd generation)" "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-" "com.apple.CoreSimulator.SimRuntime.iOS-15-2"

      - name: "Start Simulator"
        working-directory: ./scripts
        env:
          DEVICE_ID: ${{ matrix.device }}
        run: source ./ios_emulator.sh

        # JS Stuff
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.config.outputs.node-version }}

      - name: "Build JS"
        working-directory: ./scripts
        run: source ./init_env.sh && ./build_js.sh

        # Run Tests
      - name: "Flutter driver test and record video"
        working-directory: ./scripts
        run: ./ios_integration_test.sh
        env:
          TEMP_DIR:  ${{ steps.config.outputs.temp-screenshots }}
          RECORD: ${{ matrix.record_video }}

      - name: "Upload screenshots and recording"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ matrix.device }}
          path:  ${{ steps.config.outputs.temp-screenshots }}
