name: Deploy Flutter App to Appstore Connect

on:
  push:
    branches:
      - beta
      - cl/publish-test

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flutter wrapper
        run: ./scripts/install_flutter_wrapper.sh

      - name: Get dependencies (i.e., melos)
        run: .flutter/bin/dart pub get

      - name: Melos Bootstrap
        run: .flutter/bin/dart run melos bootstrap

      - name: Setup Apple Code Signing - Import Certificates and Provisioning Profiles
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERT_P12_BASE64 }}
          p12-password: ${{ secrets.CERT_P12_PASSWORD }}
          mobileprovision-file-base64: ${{ secrets.MOBILE_PROVISION_BASE64 }}

      - name: Build iOS IPA
        run: .flutter/bin/dart run melos build-ipa-release
        env:
          CI: true

      - name: Install Fastlane
        run: brew install fastlane

      - name: Upload to App Store Connect
        uses: akiojin/publish-testflight-github-action@v0.1.11
        with:
          ipa-path: app/build/ios/ipa/*.ipa
          api-key: ${{ secrets.APP_STORE_PRIVATE_KEY }}
          issuer-id: ${{ secrets.APP_STORE_ISSUER_ID }}
          key-id: ${{ secrets.APP_STORE_KEY_ID }}
