name: Deploy Flutter App to Appstore Connect

on:
  push:
    branches:
      - beta
      - cl/publish-test

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flutter wrapper
        run: ./scripts/install_flutter_wrapper.sh

      - name: Get dependencies (i.e., melos)
        run: .flutter/bin/dart pub get

      - name: Melos Bootstrap
        run: .flutter/bin/dart run melos bootstrap

      - name: Build iOS IPA
        run: .flutter/bin/dart run melos build-ipa-release
        env:
          CI: true

      - name: Deploy
        uses: vfrascello/xcode-deploy@v1.5
        with:
          xcode-version: '15.2'
          configuration: 'Release'
          scheme: 'Runner'
          path-to-export-options: 'ExportOptions.plist'
          update-build: false
          install-pods: false
          resolve-package-dependencies: true
          distribution-certificate-p12: ${{ secrets.CERT_P12_BASE64 }}
          distribution-certificate-password: ${{ secrets.CERT_P12_PASSWORD }}
          app-store-provisioning-profile: ${{ secrets.MOBILE_PROVISION_BASE64}}
          auth-key-id: ${{ secrets.APP_STORE_KEY_ID }}
          auth-key-issuer-id: ${{ secrets.APP_STORE_ISSUER_ID }}
          auth-key-p8: ${{ secrets.APP_STORE_PRIVATE_KEY }}
