name: Deploy Flutter App to Appstore Connect

on:
  push:
    branches:
      - beta
      - cl/publish-test

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flutter wrapper
        run: ./scripts/install_flutter_wrapper.sh

      - name: Get dependencies (i.e., melos)
        run: .flutter/bin/dart pub get

      - name: Melos Bootstrap
        run: .flutter/bin/dart run melos bootstrap

      # The cedvdb action can't use flutter wrapper.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version-file: pubspec.yaml

      - name: iOS Application Building...
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: cd app && flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          certificate-base64: ${{ secrets.CERT_P12_BASE64 }}
          certificate-password: ${{ secrets.CERT_P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.MOBILE_PROVISION_BASE64 }}
          keychain-password: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}

      # Used for debugging
#      - name: Show available profiles
#        if: always()
#        run: |
#          cargo install --git https://github.com/juwens/pputil.git
#          pputil list
#          pputil list-ext

      - name: Show Generated files
        run: |
          ls app/build/ios/ipa

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app --type ios \
            --file app/build/ios/ipa/*.ipa \
            --apiKey ${{ secrets.APP_STORE_CONNECT_API_KEY }} \
            --issuerId ${{ secrets.APP_STORE_ISSUER_ID }} \
            --keyId ${{ secrets.APP_STORE_PRIVATE_KEY }}
