name: Deploy Flutter App to Google Playconsole

on:
  push:
    branches:
      - beta
      - cl/android-store-publish

# Cancel a currently running workflow from the same PR, branch or tag when a new workflow is
# triggered (ref https://stackoverflow.com/a/72408109)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flutter wrapper
        run: ./scripts/install_flutter_wrapper.sh

      - name: Get dependencies (i.e., melos)
        run: .flutter/bin/dart pub get

      - name: Melos Bootstrap
        run: .flutter/bin/dart run melos bootstrap

      - name: Build Android AppBundle
        run: |
          .flutter/bin/dart run melos build-appbundle-play
          echo "Check release files"
          ls app/build/app/outputs/bundle/playRelease

      - name: Deploy to Google Play (Beta)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: org.encointer.wallet
          releaseFiles: app/build/app/outputs/bundle/playRelease/app-play-release.aab
          track: beta  # Publish to the beta track
