name: Deploy Flutter App to Appstore Connect

on:
  push:
    branches:
      - beta
      - cl/publish-test

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flutter wrapper
        run: ./scripts/install_flutter_wrapper.sh

      - name: Get dependencies (i.e., melos)
        run: .flutter/bin/dart pub get

      - name: Melos Bootstrap
        run: .flutter/bin/dart run melos bootstrap

      - name: iOS Application Building...
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: .flutter/bin/dart run melos build-ipa-release
          certificate-base64: ${{ secrets.CERT_P12_BASE64 }}
          certificate-password: ${{ secrets.CERT_P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.MOBILE_PROVISION_BASE64 }}
          keychain-password: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app --type ios \
            --file app/ios/build/Runner.ipa \
            --apiKey ${{ secrets.APPLE_STORE_CONNECT_API_KEY }} \
            --issuerId ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }} \
            --keyId ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
